services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    restart: always
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 3

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 8080:8080

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      discovery-service:
        condition: service_healthy
      user-db:
        condition: service_started
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      discovery-service:
        condition: service_healthy
      product-db:
        condition: service_started
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka

  media-service:
    build: ./media-service
    container_name: media-service
    depends_on:
      discovery-service:
        condition: service_healthy
      media-db:
        condition: service_started
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka

  user-db:
    image: mongo
    container_name: user_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - user_mongodb_data:/data/user_db

  product-db:
    image: mongo
    container_name: product_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27018:27017"
    volumes:
      - product_mongodb_data:/data/product_db

  media-db:
    image: mongo
    container_name: media_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27019:27017"
    volumes:
      - media_mongodb_data:/data/media_db

volumes:
  user_mongodb_data:
  product_mongodb_data:
  media_mongodb_data:
