spring:
  application:
    name: order-service

server:
  port: 8084
  servlet:
    context-path: /api

data:
  mongodb:
    uri: ${MONGO_URL:mongodb://buy01:buy01@localhost:27020/buy01?authSource=admin}
